[account]
username = ""
password = ""

[room]
nickname = ""
roomname = ""
password = ""

[bot]
prefixes = [ ".", "," ]
# choose one from [ Chat | Websocket | Debug | error ]
chat_level = "Chat"


# if a module calls send_message() with a really long string we'll break it
# up into a list of ~128 characters per list item, then only send this number
# of messages
message_limit = 3
# TODO probably put this in a readme
[modules.welcome]
welcome_message = "Welcome to {room}, {nick}. {username} | {handle}"
self_message = "I'm back!!!"


modules = [
# "AutoUrl", # WARNING: autourl can and will leak your IP address
# "Captcha",
# "Debug",
# "Discord",
# "Food2fork",
  "Log",
# "Movie", # UNTESTED
# "Urban",
# "Webcam",
# "WunderTime",
# "Youtube",
]
[module.admin]
vip_enabled = false
kick_as_ban = false

[module.template]
string_example = "https://tinychat.com/room/test"

[module.tokes]
hourly_420 = true


[module.autourl]
pattern = "http.\\S+"
exclusion_char = "!"
# things in url to ignore, regular expressions supported
ignores = [
"tinychat.com"
]

[module.captcha]
key = ""

[module.food2fork]
key = ""

[module.movie]
key = ""
include_url = true

[module.youtube]
key = ""

[discord]
# channel not needed for webhook
channel = ""
# TODO explain these bits
use_webhook = false
webhook_url = ""
include_avatar = false
bot.username = "TC Notification"
bot.icon_url = "https://i.imgur.com/aPDJRaE.png"
bot.message = "**{nick}** has joined the room with the account **{username}**"
