[account]
username = ""
password = ""

[room]
nickname = ""
roomname = ""
password = ""

[bot]
prefixes = [ ".", "," ]
# choose one from [ Chat | Websocket | Debug | error ]
chat_level = "Chat"
message_limit = 3

# remove the comment to enable
modules = [
# "AutoUrl", # WARNING: autourl can and will leak your IP address
# "Captcha",
# "Debug",
# "Discord",
# "Food2fork",
# "Log",
# "Movie", # UNTESTED
# "Urban",
# "Webcam",
# "WunderTime",
# "Youtube",
]

#### Module Settings ####
[module.admin]
vip_enabled = false
kick_as_ban = false

[module.autourl]
pattern = "http.\\S+"
exclusion_char = "!"
# things in url to ignore, regular expressions supported
ignores = ["tinychat.com"]

[module.captcha]
key = ""

[module.food2fork]
key = ""

[module.fun]
fancydice = true
8ballcustom = []
enablerate = false

[module.movie]
key = ""
include_url = true

[module.template]
string_example = "https://tinychat.com/room/test"

[module.tokes]
hourly_420 = true

[modules.welcome]
welcome_message = "Welcome to {room}, {nick}. {username} | {handle}"
self_message = "I'm back!!!"

[module.youtube]
key = ""

[discord]
# channel not needed for webhook
channel = ""
# TODO explain these bits
use_webhook = false
webhook_url = ""
include_avatar = false
bot.username = "TC Notification"
bot.icon_url = "https://i.imgur.com/aPDJRaE.png"
bot.message = "**{nick}** has joined the room with the account **{username}**"
