[account]
username = ""
password = ""

[room]
nickname = ""
roomname = ""
password = ""

[bot]
prefixes = [ ".", "," ]
# TODO probably put this in a readme
welcome_message = "Welcome to {room}, {nick}. {username} | {handle}"
modules = [
# "AutoUrl", # WARNING: autourl can and will leak your IP address
# "Captcha",
# "Debug",
# "Discord",
# "Food2fork",
  "Log",
# "Movie", # UNTESTED
# "Urban",
# "Webcam",
# "WunderTime",
# "Youtube",
]
[module.autourl]
pattern = "http.\\S+"
exclusion_char = "!"
# things in url to ignore, regular expressions supported
ignores = [
"tinychat.com"
]

[module.captcha]
key = ""

[module.food2fork]
key = ""

[module.movie]
key = ""
include_url = true

[module.youtube]
key = ""

[discord]
# channel not needed for webhook
channel = ""
# TODO explain these bits
use_webhook = false
webhook_url = ""
include_avatar = false
bot.username = "TC Notification"
bot.icon_url = "https://quad.pe/e/rurVj3widl.png"
bot.message = "**{nick}** has joined the room with the account **{username}**"

